In [27]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import KFold

In [28]:
# Load the datasets
df = pd.read_csv('Dataset.csv')

X_train = pd.read_csv("X_train_bin.csv")
X_test = pd.read_csv("X_test_bin.csv")
y_train = pd.read_csv("y_train_bin.csv").squeeze()
y_test = pd.read_csv("y_test_bin.csv").squeeze()

In [29]:
from sklearn.model_selection import train_test_split

# Validation Split
X_train2, X_val, y_train2, y_val = train_test_split(X_train, y_train, test_size=0.20, stratify=y_train, random_state=42)

In [30]:
best_score = -1
best_params = None
best_model = None

In [ ]:
# GridSearch 
for C in [0.01,0.1,1,10]:
    for penalty in ["l1", "l2"]:
        gs_model = LogisticRegression(
            C= C,
            penalty= penalty,
            solver= "liblinear",
            max_iter= 5000
        )
        gs_model.fit(X_train2, y_train2)
        gs_pred = gs_model.predict(X_val)
        gs_score = f1_score(y_val, gs_pred, average="weighted")
        if gs_score > best_score:
            best_score = gs_score
            best_params = {"C": C, "penalty": penalty}
            best_model = gs_model

c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\li

In [33]:
print(best_params)
print(best_score)
print(best_model)

{'C': 10, 'penalty': 'l2'}
0.9329477054251905
LogisticRegression(C=10, max_iter=5000, penalty='l2', solver='liblinear')


In [39]:
# GridSearch predictions
gs_pred = best_model.predict(X_test)

In [40]:
# calculate evaluation for GridSearch
gs_accuracy = accuracy_score(y_test, gs_pred)
gs_recall = recall_score(y_test, gs_pred)
gs_precision = precision_score(y_test, gs_pred)
gs_f1 = f1_score(y_test, gs_pred)

print(f"GrisSearch Accuracy: {gs_accuracy}")
print(f"GrisSearch Recall: {gs_recall}")
print(f"GrisSearch Precision: {gs_precision}")
print(f"GrisSearch F1 Score: {gs_f1}")

GrisSearch Accuracy: 0.9332225262254283
GrisSearch Recall: 0.8106396567388391
GrisSearch Precision: 0.8432251363768211
GrisSearch F1 Score: 0.826611386797039


In [21]:
model = LogisticRegression(max_iter= 5000)
param_grid = [
    {"penalty" : ["l1", "l2"],
     "C" : [0.01,0.1,1,10],
     "solver": ["liblinear"]}
]

In [ ]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(model, param_grid = param_grid, cv= 3, scoring= "f1_weighted", verbose= True, n_jobs= 1)

In [25]:
best_clf = clf.fit(X_train, y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits


c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:1160: UserWarning: Inconsistent values: penalty=l1 with l1_ratio=0.0. penalty is deprecated. Please use l1_ratio only.
  warnings.warn(
c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and us

In [41]:
cv_pred = best_clf.best_estimator_.predict(X_test)

In [50]:
# calculate evaluation for GridSearchCV
cv_accuracy = accuracy_score(y_test, cv_pred)
cv_recall = recall_score(y_test, cv_pred)
cv_precision = precision_score(y_test, cv_pred)
cv_f1 = f1_score(y_test, cv_pred)

print(f"GridSearchCV Accuracy: {cv_accuracy}")
print(f"GridSearchCV Recall: {cv_recall}")
print(f"GridSearchCV Precision: {cv_precision}")
print(f"GridSearchCV F1 Score: {cv_f1}")

GridSearchCV Accuracy: 0.9340262015829756
GridSearchCV Recall: 0.8119079959341183
GridSearchCV Precision: 0.8459137769447048
GridSearchCV F1 Score: 0.8285621176027796


In [45]:
print(confusion_matrix(y_test, gs_pred))

[[438225  16755]
 [ 21051  90118]]


In [46]:
print(confusion_matrix(y_test, cv_pred))

[[438539  16441]
 [ 20910  90259]]


In [47]:
print(classification_report(y_test, gs_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.96      0.96    454980
         1.0       0.84      0.81      0.83    111169

    accuracy                           0.93    566149
   macro avg       0.90      0.89      0.89    566149
weighted avg       0.93      0.93      0.93    566149



In [48]:
print(classification_report(y_test, cv_pred))

              precision    recall  f1-score   support

         0.0       0.95      0.96      0.96    454980
         1.0       0.85      0.81      0.83    111169

    accuracy                           0.93    566149
   macro avg       0.90      0.89      0.89    566149
weighted avg       0.93      0.93      0.93    566149



In [49]:
print(best_params)
print(best_clf.best_params_)

{'C': 10, 'penalty': 'l2'}
{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}


In [38]:
best_clf.best_estimator_
best_clf.best_score_
best_clf.best_params_

{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}

In [36]:
print(best_clf.best_score_)

0.9341595008093119


In [10]:
y_pred = model.predict(X_test)

In [11]:
model.score(X_test, y_test)

0.9206163041884734

In [12]:
print(confusion_matrix(y_test, y_pred))

# shap to show the influence of the features

[[437565  17415]
 [ 27528  83641]]


In [13]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.94      0.96      0.95    454980
         1.0       0.83      0.75      0.79    111169

    accuracy                           0.92    566149
   macro avg       0.88      0.86      0.87    566149
weighted avg       0.92      0.92      0.92    566149



In [ ]:
#calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Recall: {recall}")
print(f"Precision: {precision}")
print(f"F1 Score: {f1}")

Accuracy: 0.9206163041884734
Recall: 0.7523770115769683
Precision: 0.827669806839772
F1 Score: 0.7882294734362115


In [17]:
from sklearn.model_selection import StratifiedKFold

k = 3
kf = StratifiedKFold(n_splits= k, shuffle=True, random_state=42)
score = []

for train_index, test_index in kf.split(X_train, y_train):
    x_train_fold, x_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train[train_index], y_train[test_index]
    model.fit(x_train_fold, y_train_fold)
    score.append(model.score(x_test_fold, y_test_fold))


c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Vasilis\Documents\Vasilis\Programming\Εξόρυξη Δεδομένων\venvsource\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to sca

In [18]:
print('List of possible accuracy:', score)

List of possible accuracy: [0.9207474184125638, 0.9213329535744802, 0.920903632972297]
